//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSDCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HO_SO_ONLINE
    {
        public int Id { get; set; }
        public string FCode { get; set; }
        public string FName { get; set; }
        public string FDescription { get; set; }
        public Nullable<bool> FInUse { get; set; }
        public string FUserCreate { get; set; }
        public string FUserEdit { get; set; }
        public string FUserUpdate { get; set; }
        public string FUserDelete { get; set; }
        public Nullable<bool> FIsDelete { get; set; }
        public Nullable<bool> FIsEdit { get; set; }
        public Nullable<bool> FIsUpdate { get; set; }
        public Nullable<System.DateTime> FViewTime { get; set; }
        public Nullable<System.DateTime> FEditTime { get; set; }
        public Nullable<System.DateTime> FCreateTime { get; set; }
        public Nullable<System.DateTime> FUpdateTime { get; set; }
        public Nullable<System.DateTime> FDeleteTime { get; set; }
        public string FLanguage { get; set; }
        public Nullable<int> FIndex { get; set; }
        public Nullable<int> FLevel { get; set; }
        public string MaDichVu { get; set; }
        public string HoTenNguoiNop { get; set; }
        public string LoaiGiayToHL { get; set; }
        public string SoGiayTo { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<int> NamSinh { get; set; }
        public string TenCoQuan { get; set; }
        public string GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string DiaBan { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public string TrangThaiHS { get; set; }
        public string TrangThai { get; set; }
        public string TinhTrang { get; set; }
        public string NoiDungYKien { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
        public string MaDonVi { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public string TrangThaiXL { get; set; }
        public string MaNhomThuTuc { get; set; }
        public string MaKhachHang { get; set; }
        public string TenDuAn { get; set; }
        public string Level { get; set; }
        public string LevelHS { get; set; }
        public string HinhThuc { get; set; }
        public Nullable<bool> Sended_SMSZalo { get; set; }
        public Nullable<bool> Check_DoiChieu { get; set; }
        public string PayID_Apply { get; set; }
        public string FCodeOnline { get; set; }
        public Nullable<bool> OnLine { get; set; }
        public Nullable<bool> TrungTuyen { get; set; }
        public Nullable<bool> NguyenVong2 { get; set; }
        public string MaHoSoNguyenVong1 { get; set; }
    }
}
