//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSDCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HO_SO_TUYENSINH
    {
        public int Id { get; set; }
        public string FCode { get; set; }
        public string FName { get; set; }
        public string FDescription { get; set; }
        public Nullable<bool> FInUse { get; set; }
        public string FUserCreate { get; set; }
        public string FUserEdit { get; set; }
        public string FUserUpdate { get; set; }
        public string FUserDelete { get; set; }
        public Nullable<bool> FIsDelete { get; set; }
        public Nullable<bool> FIsEdit { get; set; }
        public Nullable<bool> FIsUpdate { get; set; }
        public Nullable<System.DateTime> FViewTime { get; set; }
        public Nullable<System.DateTime> FEditTime { get; set; }
        public Nullable<System.DateTime> FCreateTime { get; set; }
        public Nullable<System.DateTime> FUpdateTime { get; set; }
        public Nullable<System.DateTime> FDeleteTime { get; set; }
        public string FLanguage { get; set; }
        public Nullable<int> FIndex { get; set; }
        public Nullable<int> FLevel { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
        public string MaDonVi { get; set; }
        public string NamHoc { get; set; }
        public string HoVaTen { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string NoiSinh { get; set; }
        public string TinhNoiSinh { get; set; }
        public string HuyenNoiSinh { get; set; }
        public string XaNoiSinh { get; set; }
        public string DanToc { get; set; }
        public string SoTheBaoHiem { get; set; }
        public string CuTru { get; set; }
        public string TinhCuTru { get; set; }
        public string HuyenCuTru { get; set; }
        public string XaCuTru { get; set; }
        public string SoDienThoai { get; set; }
        public string KhiCanBaoTin { get; set; }
        public string HoTen_Cha { get; set; }
        public string DienThoai_Cha { get; set; }
        public string NgheNghiep_Cha { get; set; }
        public string NoiLamViec_Cha { get; set; }
        public string HoTen_Me { get; set; }
        public string DienThoai_Me { get; set; }
        public string NgheNghiep_Me { get; set; }
        public string NoiLamViec_Me { get; set; }
        public string NguoiGiamHo { get; set; }
        public string NguoiGiamHo_DienThoai { get; set; }
        public string NguoiGiamHo_CuTru { get; set; }
        public string NguoiGiamHo_TinhCuTru { get; set; }
        public string NguoiGiamHo_HuyenCuTru { get; set; }
        public string NguoiGiamHo_XaCuTru { get; set; }
        public string TinhTrangSucKhoe { get; set; }
        public string HocSinhTruong { get; set; }
        public Nullable<bool> CheDoChinhSach { get; set; }
        public Nullable<bool> KhuyetTatHocHoaNhap { get; set; }
        public string DoiTuongUuTien { get; set; }
        public string DiemUuTien { get; set; }
        public string LoaiXetTuyen { get; set; }
        public string MaHoSo { get; set; }
        public string ThuocDienChinhSach { get; set; }
        public string HoanThanhCTMN { get; set; }
        public Nullable<bool> IsCamKet { get; set; }
        public string GiaiThuong { get; set; }
        public string SoDinhDanhNguoiBaoTin { get; set; }
        public string GiaiThuongKhac { get; set; }
        public string DiemKhuyenKhich { get; set; }
        public string DiemKhuyenKhichKhac { get; set; }
        public string MonHocChuyen { get; set; }
        public string SoCCCDHocSinh { get; set; }
        public string NhomMonBatBuoc { get; set; }
        public string NhomMonBatBuocNV2 { get; set; }
        public string LopMamNon { get; set; }
    }
}
