//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSDCompany.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public long Id { get; set; }
        public string FCode { get; set; }
        public string FName { get; set; }
        public string FDescription { get; set; }
        public Nullable<System.DateTime> FCreateTime { get; set; }
        public Nullable<System.DateTime> FUpdateTime { get; set; }
        public string FUserCreate { get; set; }
        public string FUserApprove { get; set; }
        public Nullable<System.DateTime> FApproveTime { get; set; }
        public string FStatus { get; set; }
        public Nullable<int> FIndex { get; set; }
        public Nullable<int> FLevel { get; set; }
        public Nullable<bool> FInUse { get; set; }
        public string FBranchCode { get; set; }
        public string FUserUpdate { get; set; }
        public string title { get; set; }
        public string subtitle { get; set; }
        public string type { get; set; }
        public Nullable<bool> hidden { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> disabled { get; set; }
        public string link { get; set; }
        public string externalLink { get; set; }
        public string target { get; set; }
        public string exactMatch { get; set; }
        public string icon { get; set; }
        public string parent { get; set; }
    }
}
